name: Automatizar Roadmap desde archivo

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  roadmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install js-yaml

      - name: Crear issues desde roadmap.yaml
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            
            try {
              const file = fs.readFileSync('roadmap.yaml', 'utf8');
              const roadmap = yaml.load(file);
              
              if (!roadmap.hitos || !Array.isArray(roadmap.hitos) || roadmap.hitos.length === 0) {
                core.setFailed('No se encontraron hitos en roadmap.yaml');
                return;
              }
              
              console.log(`Encontrados ${roadmap.hitos.length} hitos en roadmap.yaml`);
              
              for (const hito of roadmap.hitos) {
                if (!hito.titulo) {
                  console.warn('Hito sin título encontrado, saltando...');
                  continue;
                }
                
                const issueData = {
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: hito.titulo,
                  body: hito.descripcion || '',
                  labels: ['roadmap']
                };
                
                console.log(`Creando issue: ${hito.titulo}`);
                const issue = await github.rest.issues.create(issueData);
                console.log(`Issue creado: #${issue.data.number} - ${issue.data.title}`);
              }
              
              console.log('Todos los issues han sido creados exitosamente');
            } catch (error) {
              core.setFailed(`Error al procesar roadmap.yaml: ${error.message}`);
            }
