name: Automatizar Roadmap desde archivo

on:
  workflow_dispatch:

jobs:
  roadmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install js-yaml

      - name: Crear issues desde roadmap.yaml
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const yaml = require('js-yaml');
            const file = fs.readFileSync('roadmap.yaml', 'utf8');
            const roadmap = yaml.load(file);

            if (!roadmap.hitos || roadmap.hitos.length === 0) {
              core.setFailed('No se encontraron hitos en roadmap.yaml');
            } else {
              for (const hito of roadmap.hitos) {
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: hito.titulo,
                  body: hito.descripcion || '',
                  labels: ['roadmap']
                });
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
